# docker-compose.yml

version: '3.5'
services:
  fe:
    build:
      context: ./frontend
      dockerfile: dockerfile
    restart: always
    command: npm run start
    container_name: fe
    ports: 
      - 80:3000
