# docker-compose.yml
version: '3.5'
services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
  backend:
    build:
      context: ./backend
    restart: always
    volumes:
      - ./db/storage:/app/storage
    ports: 
      - 8080:8080
      #  change links to virtual network
    links:
      - "db"
  db:
    build:
      context: ./db
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306