# docker-compose.yml

version: '3.5'
services:
  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    command: npm start
    container_name: fe
    ports: 
      - 443:3000
